### ISSUE TITLE
Default to mega/primal forme

### ISSUE THREAD

**Issue by Tapin42** [rushanshekar/gen6-damage-calc#13]
If there's a mega/primal forme available for a particular Pokemon, the default view should be of that one; especially for calculating defensive stats, it'd be helpful to have that come up first.  'Y'-forme, when available, should likely be preferred over 'X' forme, for no good reason.

This was suggested by Slashmolder on #nuggetbridge.

**Comment by Tapin42** [comment]
Oops.  I forgot to trigger the forme change event while auto-picking the mega.  Six-character fix, but I should've noticed it in the first place.

**Comment by Carbonific** [comment]
I feel this should only be the case for Pokemon that are more likely to be mega than not. Currently Pokemon that have meager usage of their mega stone still default to their mega form. Gengar, Aerodactyl, Tyranitar, Latios, Garchomp and Sableye are the relevant Pokemon affected by this.

**Comment by Tapin42** [comment]
While I'm not averse to the concept, help me refine the algorithm -- Gengarite is the second-most common item on Gengar, and is present 24% of the time in the Feb data (I didn't check Jan, but ISTR it's similar), compared to 65% for Focus Sash.  How would you decide a) when to default to the Mega; b) which Mega to show if there's more than one?
