### ISSUE TITLE
Ape PS!'s "pick a nature using +/-" UI

### ISSUE THREAD

**Issue by Tapin42** [rushanshekar/gen6-damage-calc#18]
http://nuggetbridge.com/forums/topic/13623-nugget-bridge-damage-calculator-bugs-feature-requests/?p=175704
- Using the "+/-" after the EV number to automatically calculate nature. It's a feature I really like in Showdown.

**Comment by Tapin42** [comment]
The more I think about this one the more I think it's just not worth it.  Nobody's asked for it since the first request, and there's enough information on the page now to render its utility fairly irrelevant.  Unless someone speaks up to keep it, I'm going to close this in four days.

**Comment by rushanshekar** [comment]
I agree with not worth it.
