### ISSUE TITLE
Slowdown in Kangaskhan

### ISSUE THREAD

**Issue by Tapin42** [rushanshekar/gen6-damage-calc#33]
Some users are reporting that using Kangaskhan now slows their browser down to the point where it actually freezes:

http://nuggetbridge.com/forums/topic/13623-nugget-bridge-damage-calculator-bugs-feature-requests/?p=179084
http://nuggetbridge.com/forums/topic/13623-nugget-bridge-damage-calculator-bugs-feature-requests/?p=179088
http://nuggetbridge.com/forums/topic/13623-nugget-bridge-damage-calculator-bugs-feature-requests/?p=179089

The issue surfaced about the same time the Parental Bond calculations went live; but while JS is certainly slow, I don't think it's _that_ slow that 256 calcs instead of 16 calcs would cause such an issue.  I've spent some time in my profiler, and selecting Kangaskhan produces a similar resource-usage spike to selecting any other 'mon.

WyrmsEye's comment may be a red herring, but:

`after a short time, I end up getting a message saying that 'shockwave plugin has crashed.'`

...this sounds like it might be related to a bad ad in the rotation too, IMO (even if it's just a matter of the combination of ad and slightly-higher-calculation-time for Kang being just enough to cause trouble).

**Comment by augmt** [comment]
We can try to refactor the code so that it runs quicker.

I want to say that $.extend is too time consuming. Do you know any other ways of deep copying an object? I see that there's [JSON.parse(JSON.stringify(obj))](http://stackoverflow.com/questions/122102/what-is-the-most-efficient-way-to-clone-an-object/5344074#5344074).

**Comment by Tapin42** [comment]
Stringify/parse will work... the other option is to just use for-in/hasOwnProperty, since it looks like (unless I'm mistaken) the only sub-objects are the array of moves.

I think I'd be quite surprised if stringify/parse is faster than $.extend for such small objects, but I guess it can't hurt to try it.

**Comment by Tapin42** [comment]
I need to take a look at the PR (thanks!), but I finally located a machine that has the slowdown, so I'll do testing with #37 on that machine.  Not going to get to it before Monday or Tuesday, unfortunately.

**Comment by Tapin42** [comment]
We've received at least one report that the issue is now better, so I'm going to close this.

**Comment by augmt** [comment]
Yay! Good job!
