### ISSUE TITLE
How should we handle duplicate NB-set Pokemon?

### ISSUE THREAD

**Issue by Tapin42** [rushanshekar/gen6-damage-calc#47]
@rushanshekar @Carbonific 

I think this is the first time it's happened, but Life Orb and KellsterCartier are using identical Hydreigons in their reports:

```
    "Life Orb's Spring 2015 Hydreigon": {
      "level": 50,
      "evs": {
        "hp": "4",
        "sa": "252",
        "sp": "252"
      },
      "nature": "Modest",
      "ability": "Levitate",
      "item": "Life Orb",
      "moves": [
        "Draco Meteor",
        "Dark Pulse",
        "Fire Blast",
        ""
      ]
    },
```

```
    "KellsterCartier's Spring 2015 Hydreigon": {
      "level": 50,
      "evs": {
        "hp": "4",
        "sa": "252",
        "sp": "252"
      },
      "nature": "Modest",
      "ability": "Levitate",
      "item": "Life Orb",
      "moves": [
        "Dark Pulse",
        "",
        "Fire Blast",
        "Draco Meteor"
      ]
    },
```

This raises the question: How should we deal with this?  IMO, I'd prefer to not add any duplicates (which in this case would mean removing Life Orb's Hydreigon).

**Comment by Tapin42** [comment]
Note that if including them both isn't the chosen answer, I can certainly write a programmatic solution to this. I just need to know what everyone feels is the best approach.

**Comment by Carbonific** [comment]
I also agree that duplicates should not be included, but that raises the definition of identical into question. If two sets have matching Natures, EVs, and Items, but different Moves, should both sets be kept? In this case the sets in question are completely identical, so I'd be in favor of keeping the more senior set (KellsterCartier's) and removing the other.

**Comment by Tapin42** [comment]
I'm personally of the opinion that differing movesets could be kept.  I'm also thinking that we might want to find a way to link to the NB reports... but one thing at a time ;-)  Rushan, do you have any opinion here?

**Comment by Tapin42** [comment]
Gonna close this one with resolution "exact duplicates get left out" by this weekend if everyone who's interested has weighed in.
