### ISSUE TITLE
Multi-hit moves and resist berries

### ISSUE THREAD

**Issue by ghost** [rushanshekar/gen6-damage-calc#55]
Apparently some people were getting false calculations when calcing a Kangaskhan low kick vs a Chople Tyranitar. It seems that both attacks experienced the chople berry's effects when the berry should be consumed after one hit.

**Comment by augmt** [comment]
Sorry for not getting to this earlier; I'm preparing to work on a substantial refactoring of the base calculator's code and I'm growing reluctant to continue updating the current calculators. Pull requests are always welcome though.

Anyways this is simple to fix and that will be coming shortly. I shudder to think what _else_ is wrong with Mega Kangaskhan.
